apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: airflow-config
  namespace: airflow 
data: 
  sql_alchemy_conn: "postgresql://admin:test123.@postgres:30614/postgresdb" 
  executor: "KubernetesExecutor"