kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: logs-pv-volume 
  labels: 
    type: local 
    app: dags 
spec: 
  storageClassName: managed-premium-retain
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: "/opt/data" 
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: logs-pv-claim
  namespace: airflow  
  labels: 
    app: dags 
spec: 
  storageClassName: managed-premium-retain 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi