apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: postgres
  namespace: airflow 
spec:
  serviceName: "postgres"
  replicas: 1 
  selector: 
    matchLabels: 
      app: postgres 
  template: 
    metadata: 
      labels: 
        app: postgres 
    spec: 
      containers: 
        - name: postgres 
          image: jmukaj/airflow-postgres:0.1.0
          imagePullPolicy: "IfNotPresent"
          command: ["airflow", "db", "init"]
          ports: 
            - containerPort: 5432 
          envFrom: 
            - configMapRef: 
                name: postgres-config 
          volumeMounts: 
            - mountPath: /var/lib/postgresql/data 
              name: postgredb 
      volumes: 
        - name: postgredb 
          persistentVolumeClaim: 
            claimName: postgres-pv-claim